########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

########################### SECRETS
secrets:
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim

include:
  ########################### SERVICES
  # PREFIX ???
  # HOSTNAME=bowie2 - defined in .env

  # CORE
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/portainer.yml
  - compose/$HOSTNAME/dozzle.yml
  - compose/$HOSTNAME/homepage.yml
  - compose/$HOSTNAME/gluetun.yml
  - compose/$HOSTNAME/filebrowser.yml
  # MEDIA
  - compose/$HOSTNAME/plex.yml
  # DOWNLOADERS
  - compose/$HOSTNAME/sabnzbd.yml
  - compose/$HOSTNAME/qbittorrent.yml
  # ARRS
  - compose/$HOSTNAME/prowlarr.yml
  #- compose/$HOSTNAME/readarr.yml
  - compose/$HOSTNAME/sonarr.yml
  - compose/$HOSTNAME/radarr.yml
  # BOOKS
  - compose/$HOSTNAME/lazylibrarian.yml

