services:
  # LazyLibrarian
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    security_opt:
      - no-new-privileges:true
    restart: "no"
    # profiles: ["media", "arrs", "all"]
    networks:
      - default
    ports:
      - "5299:5299"
    volumes:
      - $DOCKERDIR/appdata/lazylibrarian:/config
      - $DATADIR/downloads:/data/downloads
      - $DATADIR/data/media:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOCKERMODS: "linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg" #optional
