services:
  # Prowlarr
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    security_opt:
      - no-new-privileges:true
    restart: "no"
    # profiles: ["media", "arrs", "all"]
    networks:
      - default
    ports:
      - "9696:9696"
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
      - $DATADIR/downloads:/data/downloads
      - $DATADIR/data/media:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
